### ISSUE TITLE
gotoh tuners are too close to edge

### ISSUE THREAD

**Issue by bat52** [bguan/pylele#13]
![gotoh_tuners](https://github.com/user-attachments/assets/66ad77d9-2462-4ff4-90c1-bfb785bd2478)
generated by regression
pylele_test_out_3.12_ubuntu-24.04(1)/pylele2.pylele_all_assembly/gotoh_tuners/trimesh/LeleAllAssembly

**Comment by bguan** [comment]
fixed with 084d7ac
