### ISSUE TITLE
Worm tuner slits are too far from tail edge

### ISSUE THREAD

**Issue by bguan** [bguan/pylele#15]
Seems excessive.

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/1b8327a7-2e54-443c-9ae1-26e72878fbeb">

**Comment by bat52** [comment]
note for pylele2 I have added a bunch of optional parameters that allow to workaround that. https://github.com/bguan/pylele/blob/main/pylele2/pylele_worm.py
the default behavior for the "flat" body is indeed to have the slits to reach the body end, so that they are 'open'.
