### ISSUE TITLE
Weird fillet at far edge of fretboard in Pylele2

### ISSUE THREAD

**Issue by bguan** [bguan/pylele#18]
![image](https://github.com/user-attachments/assets/292b6d74-ade3-4ae4-b16f-09c522907247)

Seems to affect all backends: Trimesh, Cadquery, Blender, Solid2

**Comment by bat52** [comment]
fixed by this commit
https://github.com/bat52/pylele/commit/a935468a10336f0f663b07f303e33f18ea85c704
